### ISSUE TITLE
ClassCastException from generated code when using inheritance.

### ISSUE THREAD

**Issue by motlin** [goldmansachs/reladomo#179]
I'm getting a `ClassCastException` from within Reladomo-generated code when invoking getters and setters on a subclass. I haven't used inheritance before, so it's likely I'm doing something wrong. In that case I'd expect an error message rather than a runtime exception.

I've created a small repro. One `Book` owns many AbstractChapters. `AbstractChapter` is set up as table-per-class. AbstractChapter has the key (`bookTitle`, `chapterNumber`) and has text. A subclass, `ChapterWithQuote` extends AbstractChapter, has the same key, and adds one attribute. The full definitions are at the bottom.

When I call `ChapterWithQuote.getText()` or `setText()`, I'm getting `ClassCastException`.

```java
ChapterWithQuote chapterWithQuote = new ChapterWithQuote();
String text = chapterWithQuote.getText();
```

The error:
```
java.lang.ClassCastException: com.repro.reladomo.bug.ChapterWithQuoteData cannot be cast to com.repro.reladomo.bug.AbstractChapterData
    at com.repro.reladomo.bug.AbstractChapterAbstract.getText(AbstractChapterAbstract.java:166)
```

Coming from this cast in AbstractChapterAbstract.java:
```java
public String getText()
{
    AbstractChapterData data = (AbstractChapterData) this.zSynchronizedGetData();
    return data.getText();
}
```

And I see that `ChapterWithQuoteData` in fact does not extend `AbstractChapterData`. Both classes implement MithraDataObject and have no superclass.

```java
public class ChapterWithQuoteData
implements MithraDataObject
{
    private String bookTitle;
    private int chapterNumber;
    private String quote;
    // ...
}
```

Similar situation when I call `setText()`.

```java
ChapterWithQuote chapterWithQuote = new ChapterWithQuote();
chapterWithQuote.setText("chapter text");
```

The error:
```
java.lang.ClassCastException: com.repro.reladomo.bug.ChapterWithQuoteData cannot be cast to com.repro.reladomo.bug.AbstractChapter
    at mithra.gen.Attribute1.stringValueOf(Unknown Source)
    at com.repro.reladomo.bug.AbstractChapterCommonAbstract.zSetString(AbstractChapterCommonAbstract.java:997)
    at com.repro.reladomo.bug.AbstractChapterAbstract.setText(AbstractChapterAbstract.java:172)
```

Coming from the call to `zSetString()` in AbstractChapterAbstract.java:

```java
public void setText(String newValue)
{
    zSetString(AbstractChapterFinder.text(), newValue, false, false );
}
```

Which delegates to AbstractChapterCommonAbstract.java:
```java
protected MithraDataObject zSetString(StringAttribute attr, String newValue, boolean isReadOnly, boolean hasOptimistic)
{
    TransactionalBehavior behavior = zGetTransactionalBehaviorForWriteWithWaitIfNecessary();
    try
    {
        MithraDataObject data = behavior.getCurrentDataForWrite(this);
        // attr is generated by asm. Cast happening in stringValueOf and failing.
        String cur = attr.stringValueOf(data);
        if (cur == null)
        {
            if (newValue == null) return null;
        }
        else
        {
            if (cur.equals(newValue)) return null;
        }

        data = behavior.update(this, attr, newValue, isReadOnly, true);
        if (hasOptimistic)
        {
            zIncrementOptimiticAttribute(behavior, data);
        }

        return data;
    }

    finally
    {
        behavior.clearTempTransaction(this);
    }
}
```

Is this a bug? If not, what am I doing wrong? Is there a missing error message?

## xml definitions

AbstractChapter.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<MithraObject
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/goldmansachs/reladomo/master/reladomogen/src/main/xsd/mithraobject.xsd"
        initializePrimitivesToNull="true"
        objectType="transactional"
        superClassType="table-per-class">
    <PackageName>com.repro.reladomo.bug</PackageName>
    <ClassName>AbstractChapter</ClassName>
    <DefaultTable>ABSTRACT_CHAPTER</DefaultTable>

    <Attribute
            name="bookTitle"
            javaType="String"
            primaryKey="true"
            nullable="false"
            columnName="book_title"
            trim="false" />
    <Attribute
            name="chapterNumber"
            javaType="int"
            primaryKey="true"
            nullable="false"
            columnName="chapter_number" />
    <Attribute
            name="text"
            javaType="String"
            primaryKey="false"
            nullable="false"
            columnName="text"
            trim="false" />
</MithraObject>
```

ChapterWithQuote.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<MithraObject
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/goldmansachs/reladomo/master/reladomogen/src/main/xsd/mithraobject.xsd"
        initializePrimitivesToNull="true"
        objectType="transactional">
    <PackageName>com.repro.reladomo.bug</PackageName>
    <ClassName>ChapterWithQuote</ClassName>
    <SuperClass name="com.repro.reladomo.bug.AbstractChapter"></SuperClass>
    <DefaultTable>CHAPTER_WITH_QUOTE</DefaultTable>

    <Attribute
            name="bookTitle"
            javaType="String"
            primaryKey="true"
            nullable="false"
            columnName="book_title"
            trim="false" />
    <Attribute
            name="chapterNumber"
            javaType="int"
            primaryKey="true"
            nullable="false"
            columnName="chapter_number" />
    <Attribute
            name="quote"
            javaType="String"
            primaryKey="false"
            nullable="false"
            columnName="quote"
            trim="false" />
</MithraObject>
```

Book.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<MithraObject
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/goldmansachs/reladomo/master/reladomogen/src/main/xsd/mithraobject.xsd"
        initializePrimitivesToNull="true"
        objectType="transactional">
    <PackageName>com.repro.reladomo.bug</PackageName>
    <ClassName>Book</ClassName>
    <DefaultTable>BOOK</DefaultTable>

    <Attribute
            name="title"
            javaType="String"
            primaryKey="true"
            nullable="false"
            columnName="title"
            trim="false" />
    <Relationship
            name="chapters"
            reverseRelationshipName="book"
            relatedObject="AbstractChapter"
            relatedIsDependent="true"
            cardinality="one-to-many"
            orderBy="chapterNumber asc">
        this.title = AbstractChapter.bookTitle
    </Relationship>

</MithraObject>
```

**Comment by mohrezaei** [comment]
In ```ChapterWithQuote.xml``` try this ```SuperClass``` element:
```xml
    <SuperClass name="AbstractChapter" generated="true"/>
```

**Comment by motlin** [comment]
Yup! That gets me further for sure. It seems like it would be tricky to give a good error message in this scenario.

**Comment by motlin** [comment]
I was also using the fully-qualified class name for the superclass, which I've now changed. Thank you very much!

**Comment by mohrezaei** [comment]
No problem. The ```SuperClass``` tag is a bit overloaded and it's documented well. The best place to look are the test classes.
